server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=commerce;integratedSecurity=false;encrypt=true;trustServerCertificate=true;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: admin
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    root: DEBUG
    org:
      springframework: DEBUG

mybatis:
  mapper-locations: classpath:mapper/**/*.xml


# JWT 설정
jwt:
  secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
#  expiration: 3600000 # 1 hour in milliseconds